config/routes.rb
Rails.application.routes.draw do




  get 'relationships/create'

  get 'relationships/destroy'

if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}


  resources :users, only: [:index,:show]
  resources :conversations do
    resources :messages
  end
  resources :relationships, only: [:create, :destroy]
  resources :topics, only: [:index, :new, :create, :edit, :update, :destroy, :show, :complete] do collection do
    post :confirm
    end
  end
  resources :topic do
    resources :comments
  end




  root 'topics#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, PictureUploader

    validates :content, presence: true
    validates :image, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:edit, :update, :destroy, :show]

  def index
    @topics = Topic.all.order("id DESC")
    @topic = Topic.new
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
  end

  def new
    if params[:back]
      @topic = Topic.new(topics_params)
    else
    @topic = Topic.new
    end
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id
    if @topic.save
    redirect_to topics_path, notice:"Topicを作成しました！"
    NoticeMailer.sendmail_topic(@topic).deliver
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    # edit, update, destroyで共通コード
    if @topic.update(topics_params)
      redirect_to topics_path, notice: "ブログを更新しました！"
    else
      render 'edit'
    end
  end

  def complete
    @topic.image.retrieve_from_cache! params[:cache][:image]
    @topic.save!
  end

  def destroy
    @topic.destroy
    redirect_to topics_path, notice: "Topicを削除しました！"
  end

  def confirm
    @topic = Topic.new(topics_params)
    @user = User.find(current_user.id)

    render:new if @topic.invalid?
  end

  private
  def topics_params
    params.require(:topic).permit(:title, :content,:image)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_topics_path
    elsif action_name == 'edit'
      topic_path
    end
  end
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= @topic.errors.count %>件のエラーがあります。</h2>


      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <%= f.label :content %>
  <%= f.text_area :content, class: 'form-control input-mysize',:placeholder => "今なにしてる？" %>
  <br>

    <div class="form-group">
          <%= image_tag(@topic.image) %>
          <%= f.file_field :image %>
          <%= f.hidden_field :image_cache %>
        <br>
        </div>

  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "Topic一覧に戻る", topics_path %>

app/views/topics/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

    <h3>以下の内容で、送信する。</h3>

    <%= form_for(@topic) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.hidden_field_tag :"cache[@user.image_url]", @user.image_url %>


      <p>タイトル: <%= @topic.title %></p>
      <p>本文: <%= @topic.content %></p>
      <%= image_tag(@user.image_url) %>

      <%= f.submit "登録",class: 'btn btn-primary btn-block' %>
    <% end %>


    <%= form_for(@topic, url: new_topic_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.hidden_field_tag :"cache[@user.image_url]", @user.image_url %>
       <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/topics/index.html.erb
      <div style="text-align:center;">

<p><%= notice %></p>
  <h2>投稿一覧</h2>
  <%= link_to "投稿する", new_topic_path, class: 'btn btn-default' %>
  <h3></h3>
</div>
      <div class="container">
          <div class="row">
            <div class="col-md-6" id="tweet_text">
                <a class=DashboardProfile></a>
                  <div class="Dashbord-content">
                    <h2>Facebook風アプリ</h2>
                    <p>このサイトは練習用です</p>
                    <p>投稿を作成</p>
                     <%= form_for(@topic) do |f| %>
        
                        <br>
                        <%= f.label :content %>
                        <%= f.text_area :content, class: 'form-control input-mysize',:placeholder => "今なにしてる？" %>
                        <br>
                        <div class="form-group">
                          <%= image_tag(@topic.image) %>
                          <%= f.file_field :image %>
                          <%= f.hidden_field :image_cache %>
                        <br>
                        </div>
                        <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
                        <% end %>
                  </div>
            </div>

            <div class="col-md-6">
              <% @topics.each do |topic| %>
                <div class=tweets>
                    <div class="photo">
                      <div class="photo-size">
                       <%= profile_img(topic.user) %>
                      </div>
                    </div>
                  <div class="content-name">
                    <%= link_to topic_path(topic) do %>
                    <h4><%= topic.user.name %><% end %>さん</h4>
                  </div>

                <div class="images">
                  <td><%= image_tag topic.image.to_s %></td>
                </div>

                  <div class="topic-content">
                 <p><%= topic.content %></p>
                 </div>

                 <% if current_user.present? && current_user.id == topic.user.id %>
                   <div class="clear-box">
                    <%= link_to "編集", edit_topic_path(topic.id), class: 'btn btn-default btn-sm btn-success' %>
                    <%= link_to "削除", topic_path(topic.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
                    </div>
                  <% end %>

                </div>
              <% end %>
              <p></p>


            </div>
          </div>
      </div>

app/views/topics/new.html.erb
<div class="container">
<div class="new-topic">
  <div class="col-md-11 col-md-offset-1 col-sm-10 col-sm-offset-1" id="tweet_new">
    <h2>Topicを作成する</h2>
    <%= render 'form' %>
  </div>
</div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="blog-text">
      <p class="left"><strong>タイトル</strong></p>
      <p class="left"><%= @topic.title %></p>
      <p class="left"><strong>内容</strong></p>
      <p class="left"><%= @topic.content %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <% if current_user.id == @topic.user_id %>
      <%= link_to '編集', edit_topic_path(@topic) %> |
    <% end %>
    <%= link_to '戻る', topics_path %>
  </div>
</div>