config/routes.rb
Rails.application.routes.draw do




  get 'relationships/create'

  get 'relationships/destroy'

if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}


  resources :users, only: [:index,:show]
  resources :conversations do
    resources :messages
  end
  resources :relationships, only: [:create, :destroy]
  resources :topics, only: [:index, :new, :create, :edit, :update, :destroy, :show, :complete] do collection do
    post :confirm
    end
  end
  resources :topic do
    resources :comments
  end




  root 'topics#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exam33</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <ul>
      <div id="menu">





          <li>
            <div>
              <span>
              <%= link_to topics_path, :method => :get do %>
              <i class="fa fa-rss-square fa-2x" aria-hidden="true"></i>
              <% end %>
              </span>
              <p class="arrow_box">Topic 一覧</p>
            </div>
          </li>

          <li>
            <div>
              <span>
               <%= link_to conversations_path, :method => :get do %>
                <i class="fa fa-comments fa-2x" aria-hidden="true"></i>
                <% end %>
              </span>
              <p class="arrow_box">メッセージ</p>
            </div>
          </li>

      <% if user_signed_in? %>

          <li>
            <div>
              <span>
                <%= link_to users_path, :method => :get do %>
                <i class="fa fa-users fa-2x" aria-hidden="true"></i>
                <% end %>
              </span>
              <p class="arrow_box">他のユーザー</p>
            </div>
          </li>

          <li>
            <div>
              <span>
                <%= link_to destroy_user_session_path, :method => :delete do %>
                <i class="fa fa-sign-out fa-2x" aria-hidden="true"></i>
                <% end %>
              </span>
              <p class="arrow_box">ログアウト</p>
            </div>
          </li>


         <li>
            <div>
              <span>
                 <%= link_to edit_user_registration_path, :method => :get do %>
                <i class="fa fa-user fa-2x" aria-hidden="true"></i>
                <% end %>              </span>
              <p class="arrow_box">プロフィール</p>
            </div>
          </li>




      <% else %>



          <li>
            <div>
              <span>
            <%= link_to new_user_session_path, :method => :get do %>
            <i class="fa fa-sign-in fa-2x" aria-hidden="true"></i>
            <% end %>
              </span>
              <p class="arrow_box">ログイン</p>
            </div>
          </li>


          <li>
            <div>
              <span>
            <%= link_to new_user_registration_path, :method => :get do %>
            <i class="fa fa-user-plus fa-2x" aria-hidden="true"></i>
            <% end %>
              </span>
              <p class="arrow_box">サインアップ</p>
            </div>
          </li>



      <% end %>





</div>

    </ul>
  </header>

    <%= yield %>

   <footer>
    <p>運営会社DIVE INTO CODE株式会社</p>
    <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </footer>


</body>
</html>